### ISSUE TITLE
Suggestion - Output Format

### ISSUE THREAD

**Issue by solarisfire** [M0Rf30/shisper#1]
Is it possible to modify things so a user can pass the output format at runtime?

At the moment it's hardcoded to: --output-srt

But whisper is capable of outputting as txt, vtt, lrc, csv, json, etc.

Not sure if it's easier to have this as a separate flag, or a different command for each output type.

**Comment by M0Rf30** [comment]
you can use something like
```
shisper transcribe myfile txt
shisper play myfile txt

shisper transcribe --help
Usage:
  shisper transcribe MEDIA_FILE [SUB_FORMAT]
  shisper transcribe --help | -h
    Supported values
    txt vtt srt lrc words csv json
    Default: srt
```

**Comment by solarisfire** [comment]
Amazing! Thank you!!
