### ISSUE TITLE
Filename with dots

### ISSUE THREAD

**Issue by spackonaut** [M0Rf30/shisper#3]
If the filename contains more than one "." it skips the rest of the filename. E.g. "A2.1 conference.mp4" will be output as A2.wav and A2.srt. This is the case when quoting and non quoting.

**Comment by spackonaut** [comment]
Probably changing ${media_file%%.*} to ${media_file##.*} should work out. Not 100% sure.

**Comment by M0Rf30** [comment]
Hi and thanks for your interest, this should fix
https://github.com/M0Rf30/shisper/commit/206bd3296de9294ff20ab885368a42b5d61e1d4e

**Comment by spackonaut** [comment]
Thanks for your fast reply. Looks like it is working now :+1:
